apiVersion: v1
kind: Service
metadata:
  labels:
    service: cubestore
  name: cubestore
spec:
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3030
    - name: "3306"
      port: 3306
      targetPort: 3306
    - name: "9999"
      port: 9999
      targetPort: 9999  
  externalIPs: 
    - 0.0.0.0
  selector:
    service: cubestore
status:
  loadBalancer: {}
