apiVersion: v1
kind: ConfigMap
metadata:
  name: cube-api-schema
data:
  # Here's where you define the schema files  
  Orders.js: |
    cube(`Orders`, {
      sql: `SELECT * FROM users.orders ${
        SECURITY_CONTEXT.role.unsafeValue() !== "admin"
          ? "WHERE id % 10 = CAST(FLOOR(RAND() * 10) AS UInt32)"
          : ""
    }`,    
    
      joins: {},
    
      measures: {
        count: {
          type: `count`,
          drillMembers: [id],
        },
        amount: {
          sql: `amount`,
          type: `sum`,
        },
      },    
      dimensions: {
        id: {
          sql: `id`,
          type: `number`,
          primaryKey: true,
        },
        status: {
          sql: `status`,
          type: `string`,
        },
        completedAt: {
          sql: `completed_at`,
          type: `time`,
        },
      },
      dataSource: `default`,
    });
    