apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: cube-api
  name: cube-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: cube-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: cube-api
    spec:
      containers:
        - env: # Refer to https://cube.dev/docs/reference/environment-variables for more options            
            - name: CUBEJS_CUBESTORE_HOST
              value: "cubestore-router" # USING THIS CUBESTORE HOST BECAUSE THE CUBESTORE ROUTER SERVICE IS NAMED "CUBESTORE-ROUTER"           
            #- name: CUBEJS_REDIS_URL
            #  value: redis://redis:6379 # USING THIS REDIS URL BECAUSE THE REDIS SERVICE IS NAMED "REDIS"
          image: mycube:test3
          imagePullPolicy: Never
          name: cube-api
          ports:
            - containerPort: 3000
            - containerPort: 4000
          resources: {}          
      restartPolicy: Always   
status: {}
